[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gesture-recognition"
version = "1.0"
description = "Gesture recognition demo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "mediapipe",
  "opencv-python",
  "ruff"
]
